import os
curdir = os.getcwd()
os.chdir('1.water/FEP_GLN-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_CYS-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_VAL-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_TYR-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_ARN-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_LYN-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_HIP-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_HID-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_GLU-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_TRP-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_ARG-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_SER-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_ILE-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_HIE-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_LEU-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_MET-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_LYS-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_ASH-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_PHE-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_GLH-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_ASP-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_THR-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('1.water/FEP_ASN-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_GLN-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_CYS-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_VAL-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_TYR-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_ARN-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_LYN-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_HIP-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_HID-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_GLU-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_TRP-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_ARG-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_SER-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_ILE-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_HIE-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_LEU-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_MET-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_LYS-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_ASH-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_PHE-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_GLH-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_ASP-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_THR-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
os.chdir('2.vacuum/FEP_ASN-ALA')
os.system('sbatch submit.sh')
os.chdir('../../')
