"""Module containing the analysis for non-equilibrium (NEQ) FEP calculations.

The NEQ run script (run_neq.sh, generated by QligFEP with ``--neq``) drives a series of
forward and reverse lambda-switching simulations with the ``qdyn_neq`` engine. Each switch
writes its accumulated work to the run log (lines containing ``work accumulated``). This
module reads those work values and estimates the free energy difference with the Bennett
Acceptance Ratio (BAR), bootstrapping for uncertainty, and combines the protein and water
legs into the relative binding free energy ``ddG = dF_protein - dF_water``.

Logs are read from the directory layout produced by ``run_neq.sh``: forward switches are
written to ``neq_1_*.log`` and reverse switches to ``neq_0_*.log`` (the labels follow the
original implementation: state 1 sweeps lambda 1->0, state 0 sweeps lambda 0->1).
"""

import argparse
import glob
import os
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from scipy.optimize import brentq
from scipy.stats import gaussian_kde

from .logger import logger, setup_logger

# Boltzmann constant in the two energy units Q can report work in.
KB_KCAL = 0.0019872041  # kcal/(mol*K)
KB_KJ = 0.0083144621  # kJ/(mol*K)

# The switching work written by qdyn_neq is accumulated from Q energy components, which are
# in kcal/mol. The original analysis script treated the work as if it were already in units
# of k_B*T (i.e. it used beta = 1.0), which is the default kept here ("kT") so that results
# reproduce the original implementation.
#
# NOTE: this is very likely a units inconsistency: BAR needs beta*W to be dimensionless, so
# with work in kcal/mol the correct factor is beta = 1/(k_B*T) (~1.68 mol/kcal at 300 K),
# not 1.0. Because the BAR root is not a simple rescaling of the work, this changes the
# resulting dF (and ddG). This must be revisited with the original author before relying on
# absolute numbers; use ``--work-units kcal`` for the physically consistent computation.
DEFAULT_WORK_UNITS = "kT"


def beta_from_units(work_units: str, temperature: float) -> float:
    """Return the BAR beta factor for the requested work units (see the module note)."""
    if work_units == "kT":
        return 1.0
    if work_units == "kcal":
        return 1.0 / (KB_KCAL * temperature)
    if work_units == "kJ":
        return 1.0 / (KB_KJ * temperature)
    raise ValueError(f"Unknown work units: {work_units!r}")


def dF_to_kcal(dF: float, work_units: str, temperature: float) -> float:
    """Convert a BAR free energy expressed in the work units back to kcal/mol."""
    if work_units == "kT":
        return dF * KB_KCAL * temperature
    if work_units == "kcal":
        return dF
    if work_units == "kJ":
        return dF / (KB_KJ / KB_KCAL)
    raise ValueError(f"Unknown work units: {work_units!r}")


def read_final_work(log_path: str) -> Optional[float]:
    """Read the final accumulated switching work from a qdyn_neq log.

    Each switch prints ``At step N, work accumulated was <W> ...`` every output interval;
    the last such line holds the total switching work. Returns None if the log does not
    exist or did not terminate normally.
    """
    if not os.path.exists(log_path):
        return None
    with open(log_path) as handle:
        lines = handle.readlines()
    if not lines or "terminated normally" not in "".join(lines[-15:]):
        return None
    for line in reversed(lines):
        if "work accumulated" in line:
            try:
                return float(line.split()[6])
            except (IndexError, ValueError):
                logger.warning(f"Could not parse the work value in {log_path}")
                return None
    return None


def collect_works(folder: str) -> tuple[list[float], list[float]]:
    """Collect the final work of every completed switch under a leg directory.

    Returns (forward_works, reverse_works) gathered from neq_1_*.log and neq_0_*.log found
    recursively below ``folder``.
    """
    forward, reverse = [], []
    for log_path in glob.glob(os.path.join(folder, "**", "neq_1_*.log"), recursive=True):
        work = read_final_work(log_path)
        if work is not None:
            forward.append(work)
    for log_path in glob.glob(os.path.join(folder, "**", "neq_0_*.log"), recursive=True):
        work = read_final_work(log_path)
        if work is not None:
            reverse.append(work)
    return forward, reverse


def _bracket_root(func, x0: float = 0.0, step: float = 1.0, max_expand: int = 1000):
    """Bracket the root of a monotonically increasing function around x0."""
    f0 = func(x0)
    if f0 == 0.0:
        return x0, x0
    direction = -1.0 if f0 > 0 else 1.0  # increasing func: f(x0)>0 means the root is below
    x_prev, f_prev = x0, f0
    expand = step
    for _ in range(max_expand):
        x_new = x0 + direction * expand
        f_new = func(x_new)
        if f_new == 0.0:
            return x_new, x_new
        if (f_prev < 0) != (f_new < 0):
            return (min(x_prev, x_new), max(x_prev, x_new))
        x_prev, f_prev = x_new, f_new
        expand *= 1.5
    raise RuntimeError("Could not bracket the BAR root; check the work distributions")


def bar_delta_f(work_forward, work_reverse, beta: float = 1.0) -> float:
    """Bennett Acceptance Ratio estimate of the free energy difference.

    Solves sum_i 1/(1+exp(beta*(Wf_i - dF))) = sum_j 1/(1+exp(beta*(Wr_j + dF))) for dF.
    The work arrays are the switching works of the forward and reverse processes, in the
    energy units matching ``beta`` (see ``beta_from_units``).
    """
    wf = np.asarray(work_forward, dtype=float)
    wr = np.asarray(work_reverse, dtype=float)
    if wf.size == 0 or wr.size == 0:
        raise ValueError("BAR needs at least one forward and one reverse work value")

    def objective(dF):
        a = 1.0 / (1.0 + np.exp(beta * (wf - dF)))
        b = 1.0 / (1.0 + np.exp(beta * (wr + dF)))
        return a.sum() - b.sum()

    lo, hi = _bracket_root(objective, x0=float((wf.mean() - wr.mean()) / 2.0))
    if lo == hi:
        return lo
    return brentq(objective, lo, hi)


def work_overlap(work_forward, work_reverse) -> float:
    """Overlap of the forward and negated-reverse work distributions (0 = none, 1 = full)."""
    wf = np.asarray(work_forward, dtype=float)
    wr_neg = -np.asarray(work_reverse, dtype=float)
    if wf.size < 2 or wr_neg.size < 2 or np.ptp(wf) == 0 or np.ptp(wr_neg) == 0:
        return float("nan")
    kde_f = gaussian_kde(wf)
    kde_r = gaussian_kde(wr_neg)
    grid = np.linspace(min(wf.min(), wr_neg.min()) - 1, max(wf.max(), wr_neg.max()) + 1, 2000)
    # np.trapz was renamed to np.trapezoid in NumPy 2.0; fall back on older NumPy.
    trapezoid = getattr(np, "trapezoid", np.trapz)  # noqa: NPY201
    return float(trapezoid(np.minimum(kde_f(grid), kde_r(grid)), grid))


def bar_with_uncertainty(work_forward, work_reverse, beta=1.0, n_bootstrap=1000, rng=None):
    """BAR free energy with a bootstrap standard error and the work-distribution overlap.

    Returns (dF, dF_err, overlap).
    """
    if rng is None:
        rng = np.random.default_rng(12345)
    wf = np.asarray(work_forward, dtype=float)
    wr = np.asarray(work_reverse, dtype=float)
    dF = bar_delta_f(wf, wr, beta)

    boot = []
    for _ in range(n_bootstrap):
        wf_bs = wf[rng.integers(0, wf.size, wf.size)]
        wr_bs = wr[rng.integers(0, wr.size, wr.size)]
        try:
            boot.append(bar_delta_f(wf_bs, wr_bs, beta))
        except (RuntimeError, ValueError):
            continue
    dF_err = float(np.std(boot, ddof=1)) if len(boot) > 1 else float("nan")
    return dF, dF_err, work_overlap(wf, wr)


def analyze_leg(folder: str, beta: float, n_bootstrap: int, rng) -> dict:
    """Collect works for a single leg (protein or water) and run BAR."""
    forward, reverse = collect_works(folder)
    result = {"n_forward": len(forward), "n_reverse": len(reverse)}
    if not forward or not reverse:
        logger.warning(f"No complete forward/reverse work values found in {folder}")
        result.update({"dF": float("nan"), "dF_err": float("nan"), "overlap": float("nan")})
        return result
    dF, dF_err, overlap = bar_with_uncertainty(forward, reverse, beta, n_bootstrap, rng)
    result.update({"dF": dF, "dF_err": dF_err, "overlap": overlap})
    return result


def analyze_edge(name, protein_dir, water_dir, beta, work_units, temperature, n_bootstrap, rng):
    """Compute the relative binding free energy for one perturbation edge."""
    protein = analyze_leg(str(protein_dir), beta, n_bootstrap, rng)
    water = analyze_leg(str(water_dir), beta, n_bootstrap, rng)
    dF_p = dF_to_kcal(protein["dF"], work_units, temperature)
    dF_w = dF_to_kcal(water["dF"], work_units, temperature)
    err_p = dF_to_kcal(protein["dF_err"], work_units, temperature)
    err_w = dF_to_kcal(water["dF_err"], work_units, temperature)
    return {
        "edge": name,
        "ddG_kcal": dF_p - dF_w,
        "ddG_err_kcal": float(np.sqrt(err_p**2 + err_w**2)),
        "dF_protein_kcal": dF_p,
        "dF_water_kcal": dF_w,
        "overlap_protein": protein["overlap"],
        "overlap_water": water["overlap"],
        "n_forward_protein": protein["n_forward"],
        "n_reverse_protein": protein["n_reverse"],
        "n_forward_water": water["n_forward"],
        "n_reverse_water": water["n_reverse"],
    }


def find_edges(protein_root: Path, water_root: Path):
    """Find perturbation edges shared by the protein and water setup directories.

    Expects the setupFEP layout (e.g. 2.protein/FEP_l1_l2 and 1.water/FEP_l1_l2). Returns a
    sorted list of (name, protein_dir, water_dir).
    """
    protein_edges = {p.name: p for p in protein_root.glob("FEP_*") if p.is_dir()}
    water_edges = {p.name: p for p in water_root.glob("FEP_*") if p.is_dir()}
    shared = sorted(set(protein_edges) & set(water_edges))
    return [(name, protein_edges[name], water_edges[name]) for name in shared]


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="qligfep_neq_analyze",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="BAR analysis of non-equilibrium (NEQ) FEP switching work.",
    )
    parser.add_argument(
        "-pr",
        "--protein-root",
        dest="protein_root",
        default="2.protein",
        help="Directory holding the protein-leg FEP_* edges. Defaults to `2.protein`.",
    )
    parser.add_argument(
        "-wr",
        "--water-root",
        dest="water_root",
        default="1.water",
        help="Directory holding the water-leg FEP_* edges. Defaults to `1.water`.",
    )
    parser.add_argument(
        "-p",
        "--protein-dir",
        dest="protein_dir",
        default=None,
        help="Analyze a single edge: the protein-leg directory (used with --water-dir).",
    )
    parser.add_argument(
        "-w",
        "--water-dir",
        dest="water_dir",
        default=None,
        help="Analyze a single edge: the water-leg directory (used with --protein-dir).",
    )
    parser.add_argument(
        "-T",
        "--temperature",
        dest="temperature",
        type=float,
        default=298.0,
        help="Temperature (K) used for the kcal/mol conversion (and beta when not kT). Defaults to 298.",
    )
    parser.add_argument(
        "-u",
        "--work-units",
        dest="work_units",
        default=DEFAULT_WORK_UNITS,
        choices=["kT", "kcal", "kJ"],
        help=(
            "Units the switching work is assumed to be in for BAR. Defaults to `kT` (beta=1, "
            "reproduces the original implementation). Use `kcal` for the physically consistent "
            "computation (beta=1/kT). See the units note in this module."
        ),
    )
    parser.add_argument(
        "-nb",
        "--n-bootstrap",
        dest="n_bootstrap",
        type=int,
        default=1000,
        help="Number of bootstrap resamples for the uncertainty estimate. Defaults to 1000.",
    )
    parser.add_argument(
        "-o",
        "--output",
        dest="output",
        default="neq_results.csv",
        help="Output CSV file for the per-edge results. Defaults to `neq_results.csv`.",
    )
    parser.add_argument(
        "-rs",
        "--random_state",
        dest="random_state",
        type=int,
        default=None,
        help="Random state for the reproducible bootstrap. Defaults to None.",
    )
    parser.add_argument(
        "-log",
        "--log-level",
        dest="log",
        default="info",
        help="Set the log level for the logger. Defaults to `info`.",
        choices=["trace", "debug", "info", "warning", "error", "critical"],
    )
    return parser.parse_args()


def main(args: argparse.Namespace) -> pd.DataFrame:
    setup_logger(level=args.log.upper())
    beta = beta_from_units(args.work_units, args.temperature)
    rng = np.random.default_rng(args.random_state)

    if args.protein_dir and args.water_dir:
        edges = [(Path(args.water_dir).name, Path(args.protein_dir), Path(args.water_dir))]
    else:
        edges = find_edges(Path(args.protein_root), Path(args.water_root))
        if not edges:
            raise FileNotFoundError(
                f"No shared FEP_* edges found in {args.protein_root} and {args.water_root}"
            )

    rows = [
        analyze_edge(name, pdir, wdir, beta, args.work_units, args.temperature, args.n_bootstrap, rng)
        for name, pdir, wdir in edges
    ]
    df = pd.DataFrame(rows)
    df.to_csv(args.output, index=False)
    logger.info(f"Wrote {len(df)} edge(s) to {args.output}\n{df.to_string(index=False)}")
    return df


def main_exe():
    args = parse_arguments()
    main(args)


if __name__ == "__main__":
    main_exe()
