"""Module containing the analysis for non-equilibrium (NEQ) FEP calculations.

The NEQ run script (run_neq.sh, generated by QligFEP with ``--neq``) drives a series of
forward and reverse lambda-switching simulations with the serial ``qdyn`` engine (NEQ mode
selected by the ``[lambda_scaling]`` section). Each switch
writes its accumulated work to the run log (lines containing ``work accumulated``). This
module reads those work values and estimates the free energy difference with the Bennett
Acceptance Ratio (BAR). BAR is run within each replicate; the per-replicate
``ddG = dF_protein - dF_water`` values are averaged across replicates and reported as
mean +/- SEM, matching the NEQ2 manuscript estimator.

Logs are read from the directory layout produced by ``run_neq.sh``: forward switches are
written to ``neq_1_*.log`` and reverse switches to ``neq_0_*.log`` (the labels follow the
original implementation: state 1 sweeps lambda 1->0, state 0 sweeps lambda 0->1).

When a mapping JSON is supplied, the per-edge ddG is injected into a ``<name>_ddG.json`` copy
of it (``Q_ddG_avg``/``Q_ddG_sem``/``Q_ddG_std`` per edge), matching the equilibrium analyzer
(``analyze_FEP.py``). With an experimental key as well, the ddG is additionally compared to
experiment (correlation metrics and the shared ddG plot). Switch-completion counts and the
per-replicate slurm run status are reported as run diagnostics.
"""

import argparse
import glob
import json
import os
from collections import defaultdict
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from scipy.optimize import brentq
from scipy.stats import gaussian_kde, kendalltau, pearsonr, spearmanr

from .analysis_plotting import create_ddG_plot
from .IO import read_slurm_diagnostics
from .logger import logger, setup_logger

# Boltzmann constant in the two energy units Q can report work in.
KB_KCAL = 0.0019872041  # kcal/(mol*K)
KB_KJ = 0.0083144621  # kJ/(mol*K)

# The switching work written by qdyn (NEQ mode) is accumulated from Q energy components in
# kcal/mol. BAR needs beta*W to be dimensionless, so the physically correct factor is
# beta = 1/(k_B*T) (~1.68 mol/kcal at 300 K) -- the "kcal" default.
DEFAULT_WORK_UNITS = "kcal"


def beta_from_units(work_units: str, temperature: float) -> float:
    """Return the BAR beta factor for the requested work units (see the module note)."""
    if work_units == "kT":
        return 1.0
    if work_units == "kcal":
        return 1.0 / (KB_KCAL * temperature)
    if work_units == "kJ":
        return 1.0 / (KB_KJ * temperature)
    raise ValueError(f"Unknown work units: {work_units!r}")


def dF_to_kcal(dF: float, work_units: str, temperature: float) -> float:
    """Convert a BAR free energy expressed in the work units back to kcal/mol."""
    if work_units == "kT":
        return dF * KB_KCAL * temperature
    if work_units == "kcal":
        return dF
    if work_units == "kJ":
        return dF / (KB_KJ / KB_KCAL)
    raise ValueError(f"Unknown work units: {work_units!r}")


# A switch log is large (~10 MB), but the final ``work accumulated`` line and the
# ``terminated normally`` footer are both at the very end, so read_final_work reads only the last
# WORK_TAIL_BYTES rather than the whole file. 256 KB comfortably spans the trailing block and footer.
WORK_TAIL_BYTES = 256 * 1024


def read_final_work(log_path: str) -> Optional[float]:
    """Read the final accumulated switching work from a qdyn NEQ-mode log.

    Each switch prints ``At step N, work accumulated was <W> ...`` every output interval;
    the last such line holds the total switching work. Only the tail of the log is read (see
    ``WORK_TAIL_BYTES``). Returns None if the log does not exist or did not terminate normally.
    """
    try:
        truncated = os.path.getsize(log_path) > WORK_TAIL_BYTES
        with open(log_path, "rb") as handle:
            if truncated:
                handle.seek(-WORK_TAIL_BYTES, os.SEEK_END)
            chunk = handle.read()
    except OSError:
        return None
    # A switch killed mid-write (e.g. disk full) can leave non-UTF-8 bytes; decode leniently so a
    # corrupt log counts as an unfinished switch, not a crash.
    lines = chunk.decode("utf-8", errors="ignore").splitlines()
    if truncated and lines:
        lines = lines[1:]  # drop the partial first line left by the mid-file seek
    if not lines or "terminated normally" not in "\n".join(lines[-15:]):
        return None
    for line in reversed(lines):
        if "work accumulated" in line:
            try:
                return float(line.split()[6])
            except (IndexError, ValueError):
                logger.warning(f"Could not parse the work value in {log_path}")
                return None
    return None


def _scan_leg(leg_dir: str) -> tuple[dict, dict]:
    """Read every switch log under a leg once, grouping works by replicate and counting switches.

    This is the single reader on the analysis hot path: each log is opened exactly once, and the
    pooled work lists, switch counts and per-replicate grouping are all derived from this one
    traversal (rather than re-reading the tree to gather counts and again to group by replicate).

    Returns ``(by_rep, counts)``. ``by_rep`` maps each replicate directory name to
    ``(forward_works, reverse_works)`` over its completed switches. ``counts`` tracks attempted vs
    completed forward/reverse switches; ``read_final_work`` returns None when a switch did not
    finish (SHAKE failure, time limit, or a high-energy nearly-decoupled-ligand crash), so
    attempted-minus-completed is the ``failed`` count -- the instability the manuscript attributes
    BAR work-overlap problems to. Forward switches are neq_1_*.log, reverse are neq_0_*.log,
    gathered recursively below ``leg_dir``.
    """
    forward, reverse = defaultdict(list), defaultdict(list)
    counts = {
        "forward_attempted": 0,
        "forward_completed": 0,
        "reverse_attempted": 0,
        "reverse_completed": 0,
    }
    for pattern, works, attempted, completed in (
        ("neq_1_*.log", forward, "forward_attempted", "forward_completed"),
        ("neq_0_*.log", reverse, "reverse_attempted", "reverse_completed"),
    ):
        for log_path in glob.glob(os.path.join(leg_dir, "**", pattern), recursive=True):
            counts[attempted] += 1
            work = read_final_work(log_path)
            if work is not None:
                works[os.path.basename(os.path.dirname(log_path))].append(work)
                counts[completed] += 1
    counts["failed"] = (counts["forward_attempted"] - counts["forward_completed"]) + (
        counts["reverse_attempted"] - counts["reverse_completed"]
    )
    reps = sorted(set(forward) | set(reverse), key=lambda r: int(r) if r.isdigit() else r)
    by_rep = {rep: (forward.get(rep, []), reverse.get(rep, [])) for rep in reps}
    return by_rep, counts


def _pool_works(by_rep: dict) -> tuple[list[float], list[float]]:
    """Flatten a ``_scan_leg`` per-replicate mapping into pooled forward/reverse work lists."""
    forward = [w for fwd, _ in by_rep.values() for w in fwd]
    reverse = [w for _, rev in by_rep.values() for w in rev]
    return forward, reverse


def collect_works_with_counts(folder: str) -> tuple[list[float], list[float], dict]:
    """Collect switch works and report how many switches were attempted vs completed.

    A switch log exists once qdyn starts; ``read_final_work`` returns None when the switch
    did not finish (SHAKE failure, time limit, or a high-energy nearly-decoupled-ligand crash).
    The attempted-minus-completed difference is the count of failed switches, the instability
    the manuscript attributes BAR work-overlap problems to. Forward switches are neq_1_*.log,
    reverse are neq_0_*.log, gathered recursively below ``folder``.
    """
    by_rep, counts = _scan_leg(folder)
    forward, reverse = _pool_works(by_rep)
    return forward, reverse, counts


def collect_works(folder: str) -> tuple[list[float], list[float]]:
    """Collect the final work of every completed switch under a leg directory.

    Returns (forward_works, reverse_works) gathered from neq_1_*.log and neq_0_*.log found
    recursively below ``folder``.
    """
    forward, reverse, _ = collect_works_with_counts(folder)
    return forward, reverse


def _bracket_root(func, x0: float = 0.0, step: float = 1.0, max_expand: int = 1000):
    """Bracket the root of a monotonically increasing function around x0."""
    f0 = func(x0)
    if f0 == 0.0:
        return x0, x0
    direction = -1.0 if f0 > 0 else 1.0  # increasing func: f(x0)>0 means the root is below
    x_prev, f_prev = x0, f0
    expand = step
    for _ in range(max_expand):
        x_new = x0 + direction * expand
        f_new = func(x_new)
        if f_new == 0.0:
            return x_new, x_new
        if (f_prev < 0) != (f_new < 0):
            return (min(x_prev, x_new), max(x_prev, x_new))
        x_prev, f_prev = x_new, f_new
        expand *= 1.5
    raise RuntimeError("Could not bracket the BAR root; check the work distributions")


def bar_delta_f(work_forward, work_reverse, beta: float = 1.0) -> float:
    """Bennett Acceptance Ratio estimate of the free energy difference.

    Solves sum_i 1/(1+exp(beta*(Wf_i - dF))) = sum_j 1/(1+exp(beta*(Wr_j + dF))) for dF.
    The work arrays are the switching works of the forward and reverse processes, in the
    energy units matching ``beta`` (see ``beta_from_units``).

    This equal-weight form (no ln(n_F/n_R) sample-count term) matches the reference NEQ2
    implementation. It is exact when the forward and reverse counts are balanced -- which they
    are up to the handful of switches that fail per leg -- and keeps the estimate consistent
    with the published values.
    """
    wf = np.asarray(work_forward, dtype=float)
    wr = np.asarray(work_reverse, dtype=float)
    if wf.size == 0 or wr.size == 0:
        raise ValueError("BAR needs at least one forward and one reverse work value")

    def objective(dF):
        a = 1.0 / (1.0 + np.exp(beta * (wf - dF)))
        b = 1.0 / (1.0 + np.exp(beta * (wr + dF)))
        return a.sum() - b.sum()

    lo, hi = _bracket_root(objective, x0=float((wf.mean() - wr.mean()) / 2.0))
    if lo == hi:
        return lo
    return brentq(objective, lo, hi)


def work_overlap(work_forward, work_reverse) -> float:
    """Overlap of the forward and negated-reverse work distributions (0 = none, 1 = full)."""
    wf = np.asarray(work_forward, dtype=float)
    wr_neg = -np.asarray(work_reverse, dtype=float)
    if wf.size < 2 or wr_neg.size < 2 or np.ptp(wf) == 0 or np.ptp(wr_neg) == 0:
        return float("nan")
    kde_f = gaussian_kde(wf)
    kde_r = gaussian_kde(wr_neg)
    grid = np.linspace(min(wf.min(), wr_neg.min()) - 1, max(wf.max(), wr_neg.max()) + 1, 2000)
    # np.trapz was renamed to np.trapezoid in NumPy 2.0; fall back on older NumPy.
    trapezoid = np.trapezoid if hasattr(np, "trapezoid") else np.trapz  # noqa: NPY201
    return float(trapezoid(np.minimum(kde_f(grid), kde_r(grid)), grid))


def works_by_replicate(leg_dir: str) -> dict:
    """Group each completed switch's work by its replicate directory.

    The run layout is ``FEP_*/<temperature>/<replicate>/neq_{0,1}_*.log`` -- one directory per
    replicate seed. Returns ``{replicate_id: (forward_works, reverse_works)}`` keyed by the
    replicate directory name (e.g. ``'1'``). Forward switches are ``neq_1_*.log``, reverse are
    ``neq_0_*.log``; a switch whose log is missing or did not finish is dropped.
    """
    return _scan_leg(leg_dir)[0]


def _dF_by_rep_from_works(by_rep: dict, beta: float, work_units: str, temperature: float) -> dict:
    """BAR free energy (kcal/mol) per replicate from pre-read per-replicate works.

    Returns ``{replicate_id: dF_kcal or None}``. A replicate missing either a forward or a
    reverse switch, or whose BAR root cannot be bracketed, yields ``None``.
    """
    result = {}
    for rep, (forward, reverse) in by_rep.items():
        if not forward or not reverse:
            result[rep] = None
            continue
        try:
            result[rep] = dF_to_kcal(bar_delta_f(forward, reverse, beta), work_units, temperature)
        except (ValueError, RuntimeError):
            result[rep] = None
    return result


def leg_dF_by_replicate(leg_dir: str, beta: float, work_units: str, temperature: float) -> dict:
    """BAR free energy (kcal/mol) for each replicate of one leg.

    Returns ``{replicate_id: dF_kcal or None}``. A replicate missing either a forward or a
    reverse switch, or whose BAR root cannot be bracketed, yields ``None``.
    """
    return _dF_by_rep_from_works(works_by_replicate(leg_dir), beta, work_units, temperature)


def analyze_leg(folder: str, beta: float, work_units: str, temperature: float) -> dict:
    """Per-replicate BAR for a single leg, plus pooled data-quality diagnostics.

    Reads the leg once (``_scan_leg``) and derives everything from that single pass: the
    per-replicate dF in kcal/mol (``dF_by_rep``), the completed/failed switch counts over the
    whole leg, and the pooled forward/reverse work overlap.
    """
    by_rep, counts = _scan_leg(folder)
    forward, reverse = _pool_works(by_rep)
    if not forward or not reverse:
        logger.warning(f"No complete forward/reverse work values found in {folder}")
    return {
        "dF_by_rep": _dF_by_rep_from_works(by_rep, beta, work_units, temperature),
        "n_forward": len(forward),
        "n_reverse": len(reverse),
        "n_failed": counts["failed"],
        "overlap": work_overlap(forward, reverse),
    }


def analyze_edge(name, protein_dir, water_dir, beta, work_units, temperature) -> dict:
    """Relative binding free energy for one edge, matching the manuscript's estimator.

    BAR is run within each replicate (that replicate's forward + reverse switches) to give one
    ``dF`` per replicate per leg; ``ddG(rep) = dF_protein(rep) - dF_water(rep)`` is formed for
    each replicate present in both legs, and reported as the mean +/- SEM across replicates.
    """
    protein = analyze_leg(str(protein_dir), beta, work_units, temperature)
    water = analyze_leg(str(water_dir), beta, work_units, temperature)
    p_rep, w_rep = protein["dF_by_rep"], water["dF_by_rep"]
    # ddG(rep) = dF_protein(rep) - dF_water(rep) for reps both legs completed; the mean/SEM below
    # are order-independent, so the shared replicate set needs no sorting.
    ddg = np.array(
        [
            p - w
            for rep in set(p_rep) & set(w_rep)
            if (p := p_rep[rep]) is not None and (w := w_rep[rep]) is not None
        ],
        dtype=float,
    )
    n = int(ddg.size)
    std = float(np.std(ddg, ddof=1)) if n > 1 else float("nan")
    dF_p = [v for v in p_rep.values() if v is not None]
    dF_w = [v for v in w_rep.values() if v is not None]
    return {
        "edge": name,
        "ddG_kcal": float(np.mean(ddg)) if n else float("nan"),
        "ddG_sem_kcal": std / np.sqrt(n) if n > 1 else float("nan"),
        "ddG_std_kcal": std,
        "n_replicates": n,
        "dF_protein_kcal": float(np.mean(dF_p)) if dF_p else float("nan"),
        "dF_water_kcal": float(np.mean(dF_w)) if dF_w else float("nan"),
        "overlap_protein": protein["overlap"],
        "overlap_water": water["overlap"],
        "n_forward_protein": protein["n_forward"],
        "n_reverse_protein": protein["n_reverse"],
        "n_failed_protein": protein["n_failed"],
        "n_forward_water": water["n_forward"],
        "n_reverse_water": water["n_reverse"],
        "n_failed_water": water["n_failed"],
    }


def parse_run_diagnostics(edge_dir: str) -> list[dict]:
    """Read per-replicate run metadata from the NEQ slurm*.out files in an edge directory.

    Each file is parsed by the shared ``IO.read_slurm_diagnostics`` footer reader. Returns one
    dict per slurm*.out found (empty list if none), so missing logs degrade gracefully.
    """
    diagnostics = []
    for slurm_out in sorted(glob.glob(os.path.join(edge_dir, "slurm*.out"))):
        info = read_slurm_diagnostics(slurm_out)
        diagnostics.append(
            {"replicate": info.replicate, "runtime": info.runtime, "seed": info.seed, "status": info.status}
        )
    return diagnostics


def load_experimental_ddG(mapping_json: str, exp_key: str) -> dict:
    """Map each edge's ``FEP_<from>_<to>`` name to its experimental ddG from the mapping JSON
    (the same file used by setupFEP / qlomap). Edges lacking ``exp_key`` are skipped.
    """
    with open(mapping_json) as handle:
        mapping = json.load(handle)
    experimental = {}
    for edge in mapping.get("edges", []):
        if edge.get(exp_key) is not None:
            experimental[f"FEP_{edge['from']}_{edge['to']}"] = edge[exp_key]
    return experimental


def correlation_metrics(predicted, experimental) -> dict:
    """Agreement metrics between predicted and experimental ddG, over their finite pairs.

    R2 is the squared Pearson correlation (as reported for the manuscript comparison).
    """
    pred = np.asarray(predicted, dtype=float)
    exp = np.asarray(experimental, dtype=float)
    mask = ~(np.isnan(pred) | np.isnan(exp))
    pred, exp = pred[mask], exp[mask]
    n = int(pred.size)
    metrics = {key: float("nan") for key in ("r2", "pearson", "spearman", "kendall", "rmse", "mae")}
    metrics["n"] = n
    if n >= 1:
        metrics["rmse"] = float(np.sqrt(np.mean((pred - exp) ** 2)))
        metrics["mae"] = float(np.mean(np.abs(pred - exp)))
    if n >= 2:
        pearson = float(pearsonr(pred, exp)[0])
        metrics["pearson"] = pearson
        metrics["r2"] = pearson**2
        metrics["spearman"] = float(spearmanr(pred, exp)[0])
        metrics["kendall"] = float(kendalltau(pred, exp)[0])
    return metrics


def find_edges(protein_root: Path, water_root: Path):
    """Find perturbation edges shared by the protein and water setup directories.

    Expects the setupFEP layout (e.g. 2.protein/FEP_l1_l2 and 1.water/FEP_l1_l2). Returns a
    sorted list of (name, protein_dir, water_dir).
    """
    protein_edges = {p.name: p for p in protein_root.glob("FEP_*") if p.is_dir()}
    water_edges = {p.name: p for p in water_root.glob("FEP_*") if p.is_dir()}
    shared = sorted(set(protein_edges) & set(water_edges))
    return [(name, protein_edges[name], water_edges[name]) for name in shared]


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="qligfep_neq_analyze",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="BAR analysis of non-equilibrium (NEQ) FEP switching work.",
    )
    parser.add_argument(
        "-p",
        "--protein-dir",
        dest="protein_dir",
        default="2.protein",
        help=(
            "Path to the directory containing the protein-leg FEP_* edges. "
            "Defaults to `2.protein` in the current working directory."
        ),
    )
    parser.add_argument(
        "-w",
        "--water-dir",
        dest="water_dir",
        default="1.water",
        help=(
            "Path to the directory containing the water-leg FEP_* edges. "
            "Defaults to `1.water` in the current working directory."
        ),
    )
    parser.add_argument(
        "-pe",
        "--protein-edge",
        dest="protein_edge",
        default=None,
        help="Analyze a single edge: the protein-leg directory (used with --water-edge).",
    )
    parser.add_argument(
        "-we",
        "--water-edge",
        dest="water_edge",
        default=None,
        help="Analyze a single edge: the water-leg directory (used with --protein-edge).",
    )
    parser.add_argument(
        "-T",
        "--temperature",
        dest="temperature",
        type=float,
        default=298.0,
        help="Temperature (K) used for the kcal/mol conversion (and beta when not kT). Defaults to 298.",
    )
    parser.add_argument(
        "-u",
        "--work-units",
        dest="work_units",
        default=DEFAULT_WORK_UNITS,
        choices=["kT", "kcal", "kJ"],
        help=(
            "Units the switching work is assumed to be in for BAR. Defaults to `kcal` "
            "(beta=1/kT, the physically consistent factor). `kT` uses beta=1, treating the "
            "work as already in units of k_B*T."
        ),
    )
    parser.add_argument(
        "-o",
        "--output",
        dest="output",
        default="neq_results.csv",
        help="Output CSV file for the per-edge results. Defaults to `neq_results.csv`.",
    )
    parser.add_argument(
        "-j",
        "--json-file",
        dest="json_file",
        default=None,
        help=(
            "Mapping JSON used to run setupFEP. When given, the per-edge ddG is injected "
            "into a `<name>_ddG.json` copy of it (Q_ddG_avg/sem/std per edge). With "
            "--experimental-key, the ddG is also compared to experiment (correlation metrics + plot)."
        ),
    )
    parser.add_argument(
        "-exp",
        "--experimental-key",
        dest="experimental_key",
        default=None,
        help="Key in the mapping JSON edges holding the experimental ddG (e.g. `ddg_value`).",
    )
    parser.add_argument(
        "-t",
        "--target",
        dest="target",
        default="neq",
        help="Target name used in the plot title and output file names. Defaults to `neq`.",
    )
    parser.add_argument(
        "-norun",
        "--no-run-data",
        dest="no_run_data",
        action="store_true",
        help="Skip parsing slurm*.out run diagnostics (use when those files are absent).",
    )
    parser.add_argument(
        "-log",
        "--log-level",
        dest="log",
        default="info",
        help="Set the log level for the logger. Defaults to `info`.",
        choices=["trace", "debug", "info", "warning", "error", "critical"],
    )
    return parser.parse_args()


def main(args: argparse.Namespace) -> pd.DataFrame:
    setup_logger(level=args.log.upper())
    beta = beta_from_units(args.work_units, args.temperature)

    if args.protein_edge and args.water_edge:
        edges = [(Path(args.water_edge).name, Path(args.protein_edge), Path(args.water_edge))]
    else:
        edges = find_edges(Path(args.protein_dir), Path(args.water_dir))
        if not edges:
            raise FileNotFoundError(f"No shared FEP_* edges found in {args.protein_dir} and {args.water_dir}")

    rows = [
        analyze_edge(name, pdir, wdir, beta, args.work_units, args.temperature) for name, pdir, wdir in edges
    ]
    df = pd.DataFrame(rows)

    if args.json_file:
        results_file = args.json_file.replace(".json", "_ddG.json")
        populate_mapping_json(df, args.json_file, results_file)
        if args.experimental_key:
            df = compare_to_experiment(df, args.json_file, args.experimental_key, args.target)

    df.to_csv(args.output, index=False)
    logger.info(f"Wrote {len(df)} edge(s) to {args.output}\n{df.to_string(index=False)}")

    if not args.no_run_data:
        write_run_diagnostics(edges, args.output)
    return df


def populate_mapping_json(df: pd.DataFrame, mapping_json: str, output_file: str) -> None:
    """Inject the per-edge NEQ ddG into a copy of the mapping JSON, matching ``analyze_FEP``.

    Each edge's ``FEP_<from>_<to>`` name is matched against the results frame; a matched edge
    gains ``Q_ddG_avg``/``Q_ddG_sem``/``Q_ddG_std`` (NaN serialized as JSON null). The updated
    mapping is written to ``output_file``; the original mapping JSON is left untouched.
    """
    with open(mapping_json) as handle:
        mapping = json.load(handle)
    results = {row["edge"]: row for _, row in df.iterrows()}
    matched = 0
    for edge in mapping.get("edges", []):
        row = results.get(f"FEP_{edge['from']}_{edge['to']}")
        if row is None:
            continue
        edge.update(
            {
                "Q_ddG_avg": _nan_to_none(row["ddG_kcal"]),
                "Q_ddG_sem": _nan_to_none(row["ddG_sem_kcal"]),
                "Q_ddG_std": _nan_to_none(row["ddG_std_kcal"]),
            }
        )
        matched += 1
    with open(output_file, "w") as handle:
        json.dump(mapping, handle, indent=4)
    logger.info(f"Injected NEQ ddG into {matched} edge(s); wrote {output_file}")


def _nan_to_none(value) -> Optional[float]:
    """Return ``None`` for a missing/NaN value (so it serializes to JSON null), else a float."""
    return None if pd.isna(value) else float(value)


def compare_to_experiment(df: pd.DataFrame, mapping_json: str, exp_key: str, target: str) -> pd.DataFrame:
    """Attach experimental ddG to the results, log correlation metrics, and save the ddG plot.

    Returns the results frame with a ``ddG_exp`` column added.
    """
    experimental = load_experimental_ddG(mapping_json, exp_key)
    df = df.assign(ddG_exp=df["edge"].map(experimental))
    matched = df.dropna(subset=["ddG_exp"])
    if matched.empty:
        logger.warning("No analyzed edges matched the experimental mapping; skipping comparison.")
        return df

    metrics = correlation_metrics(matched["ddG_kcal"], matched["ddG_exp"])
    logger.info(
        f"Experimental comparison (n={metrics['n']}): R2={metrics['r2']:.3f} "
        f"Pearson={metrics['pearson']:.3f} Spearman={metrics['spearman']:.3f} "
        f"Kendall={metrics['kendall']:.3f} RMSE={metrics['rmse']:.3f} MAE={metrics['mae']:.3f}"
    )

    plot_df = pd.DataFrame(
        {
            "fep_name": matched["edge"].to_numpy(),
            "Q_ddG_avg": matched["ddG_kcal"].to_numpy(),
            "Q_ddG_sem": matched["ddG_sem_kcal"].to_numpy(),
            "ddg_value": matched["ddG_exp"].to_numpy(),
        }
    )
    fig, _ = create_ddG_plot(plot_df, target_name=target)
    plot_path = f"{target}_neq_ddG_plot.png"
    fig.savefig(plot_path, dpi=300, bbox_inches="tight")
    logger.info(f"Saved ddG plot to {plot_path}")
    return df


def write_run_diagnostics(edges, output: str) -> None:
    """Collect per-replicate slurm run diagnostics for every edge/leg and write them next to
    the results CSV (``<output>_run_data.csv``). No-op if no slurm*.out files are found.
    """
    diag_rows = []
    for name, protein_dir, water_dir in edges:
        for system, leg_dir in (("protein", protein_dir), ("water", water_dir)):
            for record in parse_run_diagnostics(str(leg_dir)):
                diag_rows.append({"edge": name, "system": system, **record})
    if not diag_rows:
        return
    diag_path = output[:-4] + "_run_data.csv" if output.endswith(".csv") else output + "_run_data.csv"
    pd.DataFrame(diag_rows).to_csv(diag_path, index=False)
    logger.info(f"Wrote run diagnostics for {len(diag_rows)} replicate(s) to {diag_path}")


def main_exe():
    args = parse_arguments()
    main(args)


if __name__ == "__main__":
    main_exe()
