"""Converts old Fortran-stype QligFEP .inp files to qgpy JSON format. 
Generates run.py, topology, FEP, MD, and qfep files for GPU execution.
"""
import argparse
import re
import glob
import os
import shutil
import stat
import shlex
import sys
import json
from collections import deque
from random import randrange
from subprocess import check_output
from string import Template


sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../Qgpu/')))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../env/')))

# Q-GPU native libraries
import IO
import topology as TOPOLOGY
import settings as SETTINGS
import md       as MD
import fep      as FEP

# This needs to be fixed!!
globaldata = {
              'Temp'       : [],
              'MDs'        : []
             }


def parse_restart_deps(inp_files):
    """Parse [files] sections from .inp files to build a restart dependency map.

    Returns dict mapping each file stem to its restart dependency stem,
    or None if the file has no restart (i.e. it's the root).
    """
    deps = {}
    for inp_path in inp_files:
        stem = os.path.basename(inp_path).split('.')[0]
        restart_dep = None
        in_files_block = False

        with open(inp_path) as f:
            for line in f:
                stripped = line.strip()
                if stripped.startswith('[') and stripped.endswith(']'):
                    in_files_block = (stripped == '[files]')
                    continue
                if in_files_block:
                    parts = stripped.split()
                    if len(parts) >= 2 and parts[0] == 'restart':
                        # restart field is like "eq1.re" - extract stem
                        restart_dep = parts[1].split('.')[0]

        deps[stem] = restart_dep
    return deps


def execution_order(restart_deps):
    """Compute execution order from restart dependency map.

    Produces radial interleaved order: eq1→eq5→midpoint, then
    forward/reverse pairs expanding outward from the midpoint (current default with start = 0.5).
    Children are sorted descending so forward chain (first lambda > 0.5)
    comes before reverse chain (first lambda < 0.5).
    """
    # Build children map (inverse of dependency)
    children = {}
    root = None
    for node, parent in restart_deps.items():
        if parent is None:
            root = node
        else:
            children.setdefault(parent, []).append(node)

    # Sort children descending so forward chain comes before reverse
    for parent in children:
        children[parent].sort(reverse=True)

    # BFS from root
    order = []
    queue = deque([root])
    while queue:
        node = queue.popleft()
        order.append(node)
        for child in children.get(node, []):
            queue.append(child)

    return order

class Random():
    """
        Gets total replicates, constructs a dictionary of random values per
        replicate
    """
    def __init__(self,replicates=10):        
        repdic = {}
        seeds = []
        for i in range(0, replicates):
            repdic[i] = randrange(0,9999)
            seeds.append(randrange(0,9999))

        globaldata['randrep'] = repdic
        globaldata['seeds'] = seeds

class Read_Submit():
    def __init__(self,oldFEP):        
        self.oldFEP = oldFEP
        self.submitfile = self.oldFEP + '/FEP_submit.sh'

        # get some data
        if os.path.isfile(self.submitfile) == True:
            self.get_data()
            
        else:
            print(">>> FATAL: can't find {}, is the specified directory generated by QligFEP?".format(self.submitfile))
            sys.exit()
        
    def get_data(self):
        with open(self.submitfile) as infile:
            for line in infile:
                line = line.split('=')
                if line[0] == 'runs':
                    globaldata['replicates']  = int(line[1])
                
                if line[0] == 'temperatures':
                    T = line[1][1:-2]
                    globaldata['Temp'].append(float(T))
                
class Create_Environment():
    def __init__(self,wd,oldFEP,overwrite):
        oldFEProot = oldFEP.split('/')[-1]
        if oldFEProot[-1] == '/':
            oldFEProot = oldFEProot[:-1]
        
        # create user specified main workdir
        IO.create_dir('{}'.format(wd),overwrite)
            
        # create FEPdir from old FEP
        IO.create_dir('{}/{}'.format(wd,oldFEProot),overwrite)
        
        # create inputfile dir
        IO.create_dir('{}/{}/{}'.format(wd,oldFEProot,'inputfiles'),overwrite)
        
        # create results dir
        IO.create_dir('{}/{}/{}'.format(wd,oldFEProot,'results'),overwrite)        

        # create temperature dirs
        for T in globaldata['Temp']:
            IO.create_dir('{}/{}/{:.1f}'.format(wd,oldFEProot,T),overwrite)

            # create replicate dirs
            for r in globaldata['randrep']:
                IO.create_dir('{}/{}/{:.1f}/{:02d}'.format(wd,oldFEProot,T,r),overwrite)
                
class Write_Topology():
    def __init__(self,wd,oldFEP):
        top = oldFEP + '/inputfiles/dualtop.top'
        oldFEProot = oldFEP.split('/')[-1]        
        
        #read the topology
        read_top  = TOPOLOGY.Read_Topology(top)
        top_data = read_top.Q()     

        # write the .json topology
        write_top = TOPOLOGY.Write_Topology(top_data)
        out_json = '{}/{}/inputfiles/dualtop.json'.format(wd,oldFEProot)
        write_top.JSON(out_json)
    
class Write_FEP():
    def __init__(self,wd,oldFEP):
        fep = oldFEP + '/inputfiles/FEP1.fep'
        oldFEProot = oldFEP.split('/')[-1]        
        
        #read the FEP file
        read_fep  = FEP.Read_Fep(fep)
        fep_data = read_fep.Q()     

        # write the .json FEP file
        write_fep = FEP.Write_Fep(fep_data)
        out_json = '{}/{}/inputfiles/FEP1.json'.format(wd,oldFEProot)
        write_fep.JSON(out_json)
        
class Write_MD():
    def __init__(self,wd,oldFEP):
        self.wd = wd
        self.oldFEP = oldFEP
        self.oldFEProot = oldFEP.split('/')[-1]
        self.lambdas = []

        # Collect all eq and md .inp files
        all_inp = sorted(glob.glob('{}/inputfiles/eq*.inp'.format(oldFEP))) + \
                  sorted(glob.glob('{}/inputfiles/md*.inp'.format(oldFEP)))

        # Build restart dependency graph w/ correct execution order
        restart_deps = parse_restart_deps(all_inp)
        globaldata['restart_deps'] = restart_deps
        bfs_order = execution_order(restart_deps)

        # Map stems to full paths for lookup
        inp_by_stem = {}
        for f in all_inp:
            stem = os.path.basename(f).split('.')[0]
            inp_by_stem[stem] = f

        mdfiles = [inp_by_stem[stem] for stem in bfs_order]

        for replicate in globaldata['randrep']:
            for i, md in enumerate(mdfiles):
                self.mdroot = md.split('/')[-1]
                self.mdroot = self.mdroot.split('.')[0]
                if not self.mdroot in globaldata['MDs']:
                    globaldata['MDs'].append(self.mdroot)

                md_data = self.construct(md)
                
                if 'md' in md or 'eq5' in md:
                    md_data['temperature'] = self.T
                
                if 'eq1' in md:
                    md_data['random_seed'] = globaldata['randrep'][replicate]
                    
                else:
                    md_data['random_seed'] = None

                # going to remove writing all MD files and implement lambdas instead
                if not md_data['lambdas'] in self.lambdas:
                    self.lambdas.append(md_data['lambdas'])    
                self.write(md_data, replicate)

        # Writing seeds and lambdas to seperate files

        IO.JSONdump(globaldata['seeds'],
                   '{}/{}/inputfiles/{}.json'.format(self.wd,
                                    self.oldFEProot,
                                    'seeds'))
        
        IO.JSONdump(self.lambdas,                    
                    '{}/{}/inputfiles/{}.json'.format(self.wd,
                                    self.oldFEProot,
                                    'lambdas'))
            
    def construct(self,md):
        read_md  = MD.Read_MD(md)
        md_data = read_md.Q()    

        return md_data
    
    def write(self,md_data, replicate):
        write_md = MD.Write_MD(md_data)
        if self.mdroot == 'eq1':
            for T in globaldata['Temp']:
                self.T = T
                self.r = replicate            
                out_json = '{}/{}/{:.1f}/{:02d}/{}.json'.format(self.wd,
                                                            self.oldFEProot,
                                                            self.T,
                                                            self.r,
                                                            self.mdroot,
                                                            )

                write_md.JSON(out_json)
            
        else:                
            out_json = '{}/{}/inputfiles/{}.json'.format(self.wd,
                                                       self.oldFEProot,
                                                       self.mdroot,
                                                      )
            
            write_md.JSON(out_json)

class Write_Qfepfile():
    def __init__(self,wd,oldFEP):
        """
            TO DO: move Q file parsing to share module
            Read qfep.inp, populate the following data:
            'workdir'           : None,
            'states'            : None,
            'offdiag_elements'  : None,
            'kT'                : None,
            'points_to_skip'    : None,
            'only_QQ'           : None,
            'gap_bins'          : None,
            'points_per_bin'    : None,
            'alpha_state'       : None,
            'linear_combination': [],
            'energy_files'      : []            
        """
        self.data = {'workdir'           : None,
                     'states'            : None,
                     'offdiag_elements'  : None,
                     'kT'                : None,
                     'points_to_skip'    : None,
                     'only_QQ'           : False,
                     'gap_bins'          : None,
                     'points_per_bin'    : None,
                     'alpha_state'       : None,
                     'linear_combination': [],
                     'energy_files'      : [] 
                    }
        
        self.wd = wd
        self.oldFEP = oldFEP
        self.oldFEProot = oldFEP.split('/')[-1]
        self.tmp = []
        
        self.read_qfep()
        
        for T in globaldata['Temp']:
            self.T = T
            for replicate in globaldata['randrep']:
                if replicate != 0:
                    continue
                self.r = replicate
                #self.data['workdir'] = '{}/{}/{:.1f}/{:02d}'.format(self.wd,
                #                                  self.oldFEProot,
                #                                  self.T,
                #                                  self.r,
                #                                 )

                self.write_qfep()
        
        
    def read_qfep(self):
        cnt = -1
        with open('{}/inputfiles/qfep.inp'.format(self.oldFEP)) as inputfile:
            for line in inputfile:
                line = line.strip()
                line = line.split()
                cnt += 1
                if cnt == 1:
                    self.data['states'] = line[0]
                    self.data['offdiag_elements'] = line[1]
                    
                if cnt == 2:
                    self.data['kT'] = line[0]
                    self.data['points_to_skip'] = line[1]
                
                if cnt == 3:
                    self.data['gap_bins'] = line[0]
                                    
                if cnt == 4:
                    self.data['points_per_bin'] = line[0]
                                                        
                if cnt == 5:
                    self.data['alpha_state'] = line[0]
                    
                if cnt == 6:
                    for combination in line:
                        self.data['linear_combination'].append(line)
                        
                if cnt > 8:
                    ener_root = line[0].split('/')[-1].split('.')[0]
                    fep1 = '{}/dualtop/output/energies.csv'.format(ener_root)
                    fep2 = '{}.json'.format(ener_root)
                    fepout = [fep1,fep2]
                    self.data['energy_files'].append(fepout) 
                    
    def write_qfep(self):
        out_json = '{}/{}/inputfiles/{}'.format(self.wd,
                                                  self.oldFEProot,
                                                  'qfep.json',
                                                 )
        with open(out_json, 'w') as outfile:
            inputs = self.data
            json.dump(inputs,outfile,indent=2) 
        
class Write_Runfile():
    def __init__(self,wd,oldFEP,cluster):
        self.qdyn = SETTINGS.ROOT + 'src/bin/qdyn.py '
        self.qfep = SETTINGS.ROOT + 'bin/qfep.py '
        self.wd = wd
        self.oldFEProot = oldFEP.split('/')[-1]                
        self.cluster = cluster
        self.n_processes = 10
        self.commands = []
        
        self.topology = '../../inputfiles/dualtop.json'
        self.fepfile  = '../../inputfiles/FEP1.json'

        restart_deps = globaldata['restart_deps']
        for mdfile in globaldata['MDs']:
            restart = restart_deps[mdfile]
            if restart is None:
                # Root step (eq1): no restart flag
                command = "    os.system('python {} -c q7-gpu -t {} -m {}.json -f {} -d {} --clean')\n".format(self.qdyn,
                                                                            self.topology,
                                                                            mdfile,
                                                                            self.fepfile,
                                                                            mdfile
                                                                           )
            else:
                command = "    os.system('python {} -c q7-gpu -t {} -m ../../inputfiles/{}.json -f {} -d {} -r {}/dualtop/output --clean')\n".format(self.qdyn,
                                                                                  self.topology,
                                                                                  mdfile,
                                                                                  self.fepfile,
                                                                                  mdfile,
                                                                                  restart
                                                                           )
            self.commands.append(command)

        # add the qfep command
        command = "    os.system('python {} -d out -i ../../inputfiles/qfep.json')\n".format(self.qfep)
        self.commands.append(command)
        
        for T in globaldata['Temp']:
            self.T = T
            for replicate in globaldata['randrep']:
                self.r = replicate
                self.py = '{}/{}/run.py'.format(wd,
                                                self.oldFEProot,
                                               )
                self.write_py()
        
    def write_py(self):
        d = {
            'runfiles': '\n'.join(self.commands),
            'processors': self.n_processes
        }

        with open('{}/src/Qgpu/templates/RUN.py'.format(SETTINGS.ROOT), 'r') as f, \
             open(self.py,'w') as outfile:
            src = Template(f.read())
            result = src.substitute(d)
            outfile.write(result)

class Write_Submitfile():
    def __init__(self,wd,oldFEP,cluster):
        self.cluster = cluster
        self.oldFEProot = oldFEP.split('/')[-1]                
        
        if self.cluster != None:
            self.sh = '{}/{}/submit.sh'.format(wd,
                                self.oldFEProot,
                               )
            
        self.write_sh()
            
    def write_sh(self):
        with open(self.sh,'w') as outfile:
            outfile.write('#!/bin/bash\n')
            # construct slurm type file
            for key in SETTINGS.SLURM[self.cluster]:
                outfile.write('#SBATCH {} {}\n'.format(key,
                                                     SETTINGS.SLURM[self.cluster][key]
                                                    ))
            for module in SETTINGS.MODULES[self.cluster]:
                outfile.write('module load {}\n'.format(module))

            outfile.write('python run.py')

class Init(object):
    def __init__(self, data):
        """
            Main loop of QligFEP module. Input is argparse dictionary from main binary.  
        
        """
        self.environment = data
        if self.environment['oldFEP'] != None:
            print("Converting old style FEP files in {}".format(self.environment['oldFEP']))
            Read_Submit(self.environment['oldFEP'])
        
        # Collect random seeds per replicate
        Random()
        
        Create_Environment(self.environment['wd'],
                           self.environment['oldFEP'],
                           self.environment['overwrite']
                          )
        
        # Needs to be split in backward compatible reading and constructing on the fly
        Write_Topology(self.environment['wd'],
                       self.environment['oldFEP']
                      )
        
        Write_FEP(self.environment['wd'],
                  self.environment['oldFEP']
                 )
        
        Write_MD(self.environment['wd'],
                 self.environment['oldFEP']
                 )
        
        Write_Qfepfile(self.environment['wd'],
                       self.environment['oldFEP']
                      )
        
        Write_Runfile(self.environment['wd'],
                      self.environment['oldFEP'],
                      self.environment['cluster']
                      )
        
        Write_Submitfile(self.environment['wd'],
                         self.environment['oldFEP'],
                         self.environment['cluster']
                      )
