"""Module containing dictionaries and functions to help handling non-default amino acid naming"""

rename_mapping = {
    "ACE": {
        "3H": "H3",
        "2H": "H2",
        "1H": "H1",
        "H2_3": "H3",
        "H2_2": "H2",
        "H2_1": "H1",
        "3HH3": "H3",
        "2HH3": "H2",
        "1HH3": "H1",
        "HH33": "H3",
        "HH32": "H2",
        "HH31": "H1",
        "C1": "C",
        "C2": "CH3",
        "O1": "O",
    },
    "NME": {
        "3HA": "H3",
        "2HA": "H2",
        "1HA": "H1",
        "HA3": "H3",
        "HA2": "H2",
        "HA1": "H1",
        "H1_3": "H3",
        "H1_2": "H2",
        "H1_1": "H1",
        "3HH3": "H3",
        "2HH3": "H2",
        "1HH3": "H1",
        "2HH2": "H2",
        "2HH1": "H1",
        "C1": "C",
        "CH3": "C",
        "CA": "C",
        "N1": "N",
        "HN1": "H",
    },
    "GLY": {
        "H1": "H",
        "H2": "H",
        "1HA": "HA3",
        "2HA": "HA2",
    },
    "ARG": {
        "H2": "H",
        "2HG": "HG3",
        "1HG": "HG2",
    },
    "GLU": {
        "H2": "H",
        "H1": "H",
        "2HB": "HB3",
        "1HB": "HB2",
        "2HG": "HG3",
        "1HG": "HG2",
    },
    "GLN": {"H2": "H", "2HG": "HG3", "1HG": "HG2"},
    "THR": {
        "H2": "H",
        "1HG2": "HG21",
        "2HG2": "HG22",
        "3HG2": "HG23",
    },
    "LEU": {"H1": "H"},
    "VAL": {
        "3HG1": "HG13",
        "2HG1": "HG12",
        "1HG1": "HG11",
        "3HG2": "HG13",
        "2HG2": "HG12",
        "1HG2": "HG11",
    },
    "ASN": {
        "3H": "H3",
        "2H": "H2",
        "1H": "H1",
        "2HB": "HB3",
        "1HB": "HB2",
        "1HD2": "HD21",
        "2HD2": "HD22",
    },
    "PRO": {
        "2H": "H3",
        "1H": "H2",
        "2HG": "HG3",
        "1HG": "HG2",
    },
    "ALA": {
        "1HB": "HB1",
        "2HB": "HB2",
        "3HB": "HB3",
    },
    "PHE": {
        "2HB": "HB3",
        "1HB": "HB2",
    },
    "TYR": {
        "2HB": "HB3",
        "1HB": "HB2",
    },
    "SER": {
        "2HB": "HB3",
        "1HB": "HB2",
    },
    "LYS": {
        "2HG": "HG3",
        "1HG": "HG2",
    },
    "ILE": {
        "2HG": "HG3",
        "1HG": "HG2",
    },
}
