"""Module containing dictionaries and functions to help handling non-default atom naming.

Covers amino acids, DNA nucleotides (Maestro -> AMBER14sb), and ions.
"""

# Sugar hydrogen renaming shared across all DNA nucleotide types (Maestro -> AMBER14sb)
_DNA_SUGAR_RENAME = {
    "H5'1": "H5'",
    "H5'2": "H5''",
    "HC4'": "H4'",
    "HC3'": "H3'",
    "H2'1": "H2'",
    "H2'2": "H2''",
    "HC1'": "H1'",
}

rename_mapping = {
    "ACE": {
        "3H": "H3",
        "2H": "H2",
        "1H": "H1",
        "H2_3": "H3",
        "H2_2": "H2",
        "H2_1": "H1",
        "3HH3": "H3",
        "2HH3": "H2",
        "1HH3": "H1",
        "HH33": "H3",
        "HH32": "H2",
        "HH31": "H1",
        "C1": "C",
        "C2": "CH3",
        "O1": "O",
    },
    "NME": {
        "3HA": "H3",
        "2HA": "H2",
        "1HA": "H1",
        "HA3": "H3",
        "HA2": "H2",
        "HA1": "H1",
        "H1_3": "H3",
        "H1_2": "H2",
        "H1_1": "H1",
        "3HH3": "H3",
        "2HH3": "H2",
        "1HH3": "H1",
        "HH33": "H3",
        "HH32": "H2",
        "HH31": "H1",
        "2HH2": "H2",
        "2HH1": "H1",
        "C1": "C",
        "CH3": "C",
        "CA": "C",
        "N1": "N",
        "HN1": "H",
    },
    "GLY": {
        "1HA": "HA3",
        "2HA": "HA2",
    },
    "ARG": {
        "2HG": "HG3",
        "1HG": "HG2",
    },
    "GLU": {
        "2HB": "HB3",
        "1HB": "HB2",
        "2HG": "HG3",
        "1HG": "HG2",
    },
    "GLN": {"2HG": "HG3", "1HG": "HG2"},
    "THR": {
        "1HG2": "HG21",
        "2HG2": "HG22",
        "3HG2": "HG23",
    },
    "LEU": {},
    "VAL": {
        "3HG1": "HG13",
        "2HG1": "HG12",
        "1HG1": "HG11",
        "3HG2": "HG23",
        "2HG2": "HG22",
        "1HG2": "HG21",
    },
    "ASN": {
        "3H": "H3",
        "2H": "H2",
        "1H": "H1",
        "2HB": "HB3",
        "1HB": "HB2",
        "1HD2": "HD21",
        "2HD2": "HD22",
        "HD1": "HD21",
        "HD2": "HD22",
    },
    "PRO": {
        "2H": "H3",
        "1H": "H2",
        "2HG": "HG3",
        "1HG": "HG2",
    },
    "ALA": {
        "1HB": "HB1",
        "2HB": "HB2",
        "3HB": "HB3",
    },
    "PHE": {
        "2HB": "HB3",
        "1HB": "HB2",
    },
    "TYR": {
        "2HB": "HB3",
        "1HB": "HB2",
    },
    "SER": {
        "2HB": "HB3",
        "1HB": "HB2",
    },
    "LYS": {
        "2HG": "HG3",
        "1HG": "HG2",
    },
    "MET": {
        "1HE": "HE1",
        "2HE": "HE2",
        "3HE": "HE3",
    },
    "ILE": {
        "2HG": "HG3",
        "1HG": "HG2",
    },
    # DNA nucleotides: Maestro hydrogen naming -> AMBER14sb (BSC1)
    "DA": {
        **_DNA_SUGAR_RENAME,
        "HC8": "H8",
        "H6_1": "H61",
        "H6_2": "H62",
        "HC2": "H2",
    },
    "DC": {
        **_DNA_SUGAR_RENAME,
        "H4_1": "H41",
        "H4_2": "H42",
        "HC5": "H5",
        "HC6": "H6",
    },
    "DG": {
        **_DNA_SUGAR_RENAME,
        "HC8": "H8",
        "HN1": "H1",
        "H2_1": "H21",
        "H2_2": "H22",
    },
    "DT": {
        **_DNA_SUGAR_RENAME,
        "HN3": "H3",
        "H7_1": "H71",
        "H7_2": "H72",
        "H7_3": "H73",
        "HC6": "H6",
    },
}
